#!/bin/bash

ARGS=${@};

go env;

if [ -e "scripts/build" ]; then
  build ${ARGS};
else
  echo 'No custom build script found. Using default'
  go build -a -ldflags '-w -s' -o app.${GOOS}.${GOARCH};
  if [ "${GOOS}" = "windows" ]; then
    mv app.${GOOS}.${GOARCH} app.${GOOS}.${GOARCH}.exe;
  fi;
fi;
