#!/bin/bash

# import shared functions
. /scripts/shared

CURDIR=$(dirname $0);

noop()
{
  printf -- '';
}

ARG="$1";
shift 1;
ARGS="$@";

case $ARG in
  'build')
    ${CURDIR}/build ${ARGS};
    exit 0;
  ;;
  'test')
    ${CURDIR}/test ${ARGS};
    exit 0;
  ;;
  'init')
    ${CURDIR}/init;
    exit 0;
  ;;
  'shell')
    ${CURDIR}/shell ${ARGS};
    exit;
  ;;
  'start')
    ${CURDIR}/start ${ARGS};
    exit 0;
  ;;
  'help')
    noop;
  ;&
  *)
    ${CURDIR}/help;
  ;;
esac;
