#!/bin/sh

echo '
containerized scripts for golang development


';

printf -- 'machine information\n';
printf -- "ip address : $(ip addr show eth0 | grep inet | tr -s ' ' ' ' | cut -f 3 -d ' ' | cut -f 1 -d '/')\n";
printf -- "hostname  : $(hostname)\n";
printf -- "user      : $(whoami &>/dev/null)\n";
printf -- "user id   : $(id -u)\n";
printf -- "directory : $(pwd)\n";
printf -- '\n';
printf -- "args: ${@}"
printf -- "arg: $@"

#bash -l;
