#!/bin/bash
ALL_PARAMETERS=$@;
BUILED_FAILED=0;
APP_PID=0;

# use set -e only for first run because if
# application cannot build then there's no use
# retrying
update_dependencies;
build_it;
if [ $BUILD_FAILED -eq 0 ]; then run_it; else APP_PID=0; fi;


# create the watch pattern - check if there
# are any .go files and **/*.go files before adding
# it to a pattern we will use later for inotifywatch
WATCH_PATTERN='';
ls *.go &>/dev/null && STAR_GO=1 || STAR_GO=0;
ls **/*.go &>/dev/null && STAR_STAR_GO=1 || STAR_STAR_GO=0;
if [ $STAR_GO -eq 1 ]; then
  WATCH_PATTERN="*.go ${WATCH_PATTERN}"
fi;
if [ $STAR_STAR_GO -eq 1 ]; then
  WATCH_PATTERN="**/*.go ${WATCH_PATTERN}"
fi;


# start the application and watch it
INIT=0;
echo pattern ${WATCH_PATTERN}
inotifywait \
  -e create,modify \
  -m ${WATCH_PATTERN} \
  @./app |
while read -r directory events filename; do
  if [ ${INIT} -ne 0 ]; then
    if [ ${APP_PID} -ne 0 ]; then kill_it; fi;
    update_dependencies;
    build_it;
    if [ ${BUILD_FAILED} -eq 0 ]; then run_it; fi;
  fi;
  INIT=1;
done;
